obj-$(CONFIG_BLK_DEV_IDECD)	+=              cdrom.o
obj-$(CONFIG_BLK_DEV_SR)	+=              cdrom.o
obj-$(CONFIG_PARIDE_PCD)	+=		cdrom.o
obj-$(CONFIG_CDROM_PKTCDVD)	+=		cdrom.o

obj-$(CONFIG_VIOCD)		+= viocd.o      cdrom.o
obj-$(CONFIG_GDROM)		+= gdrom.o      cdrom.o
