

/* messages define for BFA_AEN_CAT_RPORT Module */
#ifndef	__bfa_aen_rport_h__
#define	__bfa_aen_rport_h__

#include  <cs/bfa_log.h>
#include  <defs/bfa_defs_aen.h>

#define BFA_AEN_RPORT_ONLINE \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_RPORT, BFA_RPORT_AEN_ONLINE)
#define BFA_AEN_RPORT_OFFLINE \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_RPORT, BFA_RPORT_AEN_OFFLINE)
#define BFA_AEN_RPORT_DISCONNECT \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_RPORT, BFA_RPORT_AEN_DISCONNECT)
#define BFA_AEN_RPORT_QOS_PRIO \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_RPORT, BFA_RPORT_AEN_QOS_PRIO)
#define BFA_AEN_RPORT_QOS_FLOWID \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_RPORT, BFA_RPORT_AEN_QOS_FLOWID)

#endif

