

/* messages define for BFA_AEN_CAT_LPORT Module */
#ifndef	__bfa_aen_lport_h__
#define	__bfa_aen_lport_h__

#include  <cs/bfa_log.h>
#include  <defs/bfa_defs_aen.h>

#define BFA_AEN_LPORT_NEW \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NEW)
#define BFA_AEN_LPORT_DELETE \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_DELETE)
#define BFA_AEN_LPORT_ONLINE \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_ONLINE)
#define BFA_AEN_LPORT_OFFLINE \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_OFFLINE)
#define BFA_AEN_LPORT_DISCONNECT \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_DISCONNECT)
#define BFA_AEN_LPORT_NEW_PROP \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NEW_PROP)
#define BFA_AEN_LPORT_DELETE_PROP \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_DELETE_PROP)
#define BFA_AEN_LPORT_NEW_STANDARD \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NEW_STANDARD)
#define BFA_AEN_LPORT_DELETE_STANDARD \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_DELETE_STANDARD)
#define BFA_AEN_LPORT_NPIV_DUP_WWN \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NPIV_DUP_WWN)
#define BFA_AEN_LPORT_NPIV_FABRIC_MAX \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NPIV_FABRIC_MAX)
#define BFA_AEN_LPORT_NPIV_UNKNOWN \
	BFA_LOG_CREATE_ID(BFA_AEN_CAT_LPORT, BFA_LPORT_AEN_NPIV_UNKNOWN)

#endif

