
#ifndef _C2_AE_H_
#define _C2_AE_H_


enum c2_event_id {
	CCAE_REMOTE_SHUTDOWN = 0x80,
	CCAE_ACTIVE_CONNECT_RESULTS,
	CCAE_CONNECTION_REQUEST,
	CCAE_LLP_CLOSE_COMPLETE,
	CCAE_TERMINATE_MESSAGE_RECEIVED,
	CCAE_LLP_CONNECTION_RESET,
	CCAE_LLP_CONNECTION_LOST,
	CCAE_LLP_SEGMENT_SIZE_INVALID,
	CCAE_LLP_INVALID_CRC,
	CCAE_LLP_BAD_FPDU,
	CCAE_INVALID_DDP_VERSION,
	CCAE_INVALID_RDMA_VERSION,
	CCAE_UNEXPECTED_OPCODE,
	CCAE_INVALID_DDP_QUEUE_NUMBER,
	CCAE_RDMA_READ_NOT_ENABLED,
	CCAE_RDMA_WRITE_NOT_ENABLED,
	CCAE_RDMA_READ_TOO_SMALL,
	CCAE_NO_L_BIT,
	CCAE_TAGGED_INVALID_STAG,
	CCAE_TAGGED_BASE_BOUNDS_VIOLATION,
	CCAE_TAGGED_ACCESS_RIGHTS_VIOLATION,
	CCAE_TAGGED_INVALID_PD,
	CCAE_WRAP_ERROR,
	CCAE_BAD_CLOSE,
	CCAE_BAD_LLP_CLOSE,
	CCAE_INVALID_MSN_RANGE,
	CCAE_INVALID_MSN_GAP,
	CCAE_IRRQ_OVERFLOW,
	CCAE_IRRQ_MSN_GAP,
	CCAE_IRRQ_MSN_RANGE,
	CCAE_IRRQ_INVALID_STAG,
	CCAE_IRRQ_BASE_BOUNDS_VIOLATION,
	CCAE_IRRQ_ACCESS_RIGHTS_VIOLATION,
	CCAE_IRRQ_INVALID_PD,
	CCAE_IRRQ_WRAP_ERROR,
	CCAE_CQ_SQ_COMPLETION_OVERFLOW,
	CCAE_CQ_RQ_COMPLETION_ERROR,
	CCAE_QP_SRQ_WQE_ERROR,
	CCAE_QP_LOCAL_CATASTROPHIC_ERROR,
	CCAE_CQ_OVERFLOW,
	CCAE_CQ_OPERATION_ERROR,
	CCAE_SRQ_LIMIT_REACHED,
	CCAE_QP_RQ_LIMIT_REACHED,
	CCAE_SRQ_CATASTROPHIC_ERROR,
	CCAE_RNIC_CATASTROPHIC_ERROR
/* WARNING If you add more id's, make sure their values fit in eight bits. */
};

enum c2_resource_indicator {
	C2_RES_IND_QP = 1,
	C2_RES_IND_EP,
	C2_RES_IND_CQ,
	C2_RES_IND_SRQ,
};

#endif /* _C2_AE_H_ */
