obj-$(CONFIG_BFIN561_ACVILON)          += acvilon.o
obj-$(CONFIG_BFIN561_BLUETECHNIX_CM)   += cm_bf561.o
obj-$(CONFIG_BFIN561_EZKIT)            += ezkit.o
obj-$(CONFIG_BFIN561_TEPLA)            += tepla.o
