snd-util-mem-objs := util_mem.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_EMU10K1) += snd-util-mem.o
obj-$(CONFIG_SND_TRIDENT) += snd-util-mem.o
obj-$(CONFIG_SND_SBAWE_SEQ) += snd-util-mem.o
obj-$(CONFIG_SND_SEQUENCER) += emux/
