obj-$(CONFIG_INFINIBAND_EHCA) += ib_ehca.o

ib_ehca-objs  = ehca_main.o ehca_hca.o ehca_mcast.o ehca_pd.o ehca_av.o ehca_eq.o \
		ehca_cq.o ehca_qp.o ehca_sqp.o ehca_mrmw.o ehca_reqs.o ehca_irq.o \
		ehca_uverbs.o ipz_pt_fn.o hcp_if.o hcp_phyp.o

