obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2443)	+= s3c2443.o
obj-$(CONFIG_CPU_S3C2443)	+= irq.o
obj-$(CONFIG_CPU_S3C2443)	+= clock.o

obj-$(CONFIG_S3C2443_DMA)	+= dma.o

# Machine support

obj-$(CONFIG_MACH_SMDK2443)	+= mach-smdk2443.o
