snd-powermac-objs := powermac.o pmac.o awacs.o burgundy.o daca.o tumbler.o keywest.o beep.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_POWERMAC)	+= snd-powermac.o
obj-$(CONFIG_SND_PS3)		+= snd_ps3.o
