snd-rme9652-objs := rme9652.o
snd-hdsp-objs := hdsp.o
snd-hdspm-objs := hdspm.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_RME9652) += snd-rme9652.o
obj-$(CONFIG_SND_HDSP) += snd-hdsp.o
obj-$(CONFIG_SND_HDSPM) +=snd-hdspm.o
