BOARD_USES_YUSU_VIDEO_DECODER_OUTPUT_FORMAT := true
# BOARD_USES_YUSU_MPEG4_HW_DECODER := true
BOARD_USES_YUSU_OMX_PMEM := true
# BOARD_USES_YUSU_MPEG4_HW_DECODER_V2 := true
BOARD_USES_6573_MFV_HW := true
BOARD_USES_ASYNC_FILE_IO := false
#BOARD_USES_YUSU_OMX_PROFILING := true
# MTK, Ryan & Jackal, 20090721, Add MPEG4 }

# MTK, TeChien, 20090731, Add MPEG4 {
# BOARD_USES_YUSU_MPEG4_HW_ENCODER := true
# BOARD_USES_YUSU_MPEG4_ENCODE_INPUT_MTKYUV := true
# MTK, TeChien, 20090731, Add MPEG4 }
