


#ifndef __FCS_TRCMOD_H__
#define __FCS_TRCMOD_H__

#include <cs/bfa_trc.h>

enum {
	BFA_TRC_FCS_FABRIC		= 1,
	BFA_TRC_FCS_VFAPI		= 2,
	BFA_TRC_FCS_PORT		= 3,
	BFA_TRC_FCS_VPORT		= 4,
	BFA_TRC_FCS_VP_API		= 5,
	BFA_TRC_FCS_VPS			= 6,
	BFA_TRC_FCS_RPORT		= 7,
	BFA_TRC_FCS_FCPIM		= 8,
	BFA_TRC_FCS_FCPTM		= 9,
	BFA_TRC_FCS_NS			= 10,
	BFA_TRC_FCS_SCN			= 11,
	BFA_TRC_FCS_LOOP		= 12,
	BFA_TRC_FCS_UF			= 13,
	BFA_TRC_FCS_PPORT		= 14,
	BFA_TRC_FCS_FCPIP		= 15,
	BFA_TRC_FCS_PORT_API	= 16,
	BFA_TRC_FCS_RPORT_API	= 17,
	BFA_TRC_FCS_AUTH		= 18,
	BFA_TRC_FCS_N2N			= 19,
	BFA_TRC_FCS_MS			= 20,
	BFA_TRC_FCS_FDMI		= 21,
	BFA_TRC_FCS_RPORT_FTRS	= 22,
};

#endif /* __FCS_TRCMOD_H__ */
