obj-y += asic-calliope.o asic-cronus.o asic-zeus.o asic_devices.o asic_int.o \
	 irq_asic.o prealloc-calliope.o prealloc-cronus.o \
	 prealloc-cronuslite.o prealloc-zeus.o

EXTRA_CFLAGS += -Wall -Werror
