

#ifndef _CAMERA_INFO_HI342_H
#define _CAMERA_INFO_HI342_H

#define SENSOR_ID                           HI342_SENSOR_ID
#define SENSOR_DRVNAME                      SENSOR_DRVNAME_HI342_RAW
#define INCLUDE_FILENAME_ISP_REGS_PARAM     "camera_isp_regs_hi342_mt6573.h"
#define INCLUDE_FILENAME_ISP_PCA_PARAM      "camera_isp_pca_hi342_mt6573.h"
#include "camera_3A_para_hi342_mt6573.h"
#define CAMERA_3A_PARA                      HI342_CAMERA_3A_PARA
#define CAMERA_3A_STAT_CONFIG_PARAM         HI342_CAMERA_3A_STAT_CONFIG_PARAM


#if defined(ISP_SUPPORT)

#define HI342_CAMERA_AUTO_DSC CAM_AUTO_DSC
#define HI342_CAMERA_PORTRAIT CAM_PORTRAIT
#define HI342_CAMERA_LANDSCAPE CAM_LANDSCAPE
#define HI342_CAMERA_SPORT CAM_SPORT
#define HI342_CAMERA_FLOWER CAM_FLOWER
#define HI342_CAMERA_NIGHTSCENE CAM_NIGHTSCENE
#define HI342_CAMERA_DOCUMENT CAM_DOCUMENT
#define HI342_CAMERA_ISO_ANTI_HAND_SHAKE CAM_ISO_ANTI_HAND_SHAKE
#define HI342_CAMERA_ISO100 CAM_ISO100
#define HI342_CAMERA_ISO200 CAM_ISO200
#define HI342_CAMERA_ISO400 CAM_ISO400
#define HI342_CAMERA_ISO800 CAM_ISO800
#define HI342_CAMERA_ISO1600 CAM_ISO1600
#define HI342_CAMERA_VIDEO_AUTO CAM_VIDEO_AUTO
#define HI342_CAMERA_VIDEO_NIGHT CAM_VIDEO_NIGHT
#define HI342_CAMERA_NO_OF_SCENE_MODE CAM_NO_OF_SCENE_MODE

#endif
#endif
